// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.153.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Excel
{
    using global::System;
    using global::System.CodeDom.Compiler;
    using global::System.Collections.Concurrent;
    using global::System.Collections.Generic;
    using global::System.Collections.ObjectModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Globalization;
    using global::System.Linq;

    using global::OBeautifulCode.Cloning.Recipes;
    using global::OBeautifulCode.Equality.Recipes;
    using global::OBeautifulCode.Type;
    using global::OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    [Serializable]
    public partial class TextDataValidation : IModel<TextDataValidation>
    {
        /// <summary>
        /// Determines whether two objects of type <see cref="TextDataValidation"/> are equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are equal; otherwise false.</returns>
        public static bool operator ==(TextDataValidation left, TextDataValidation right)
        {
            if (ReferenceEquals(left, right))
            {
                return true;
            }

            if (ReferenceEquals(left, null) || ReferenceEquals(right, null))
            {
                return false;
            }

            var result = left.Equals(right);

            return result;
        }

        /// <summary>
        /// Determines whether two objects of type <see cref="TextDataValidation"/> are not equal.
        /// </summary>
        /// <param name="left">The object to the left of the equality operator.</param>
        /// <param name="right">The object to the right of the equality operator.</param>
        /// <returns>true if the two items are not equal; otherwise false.</returns>
        public static bool operator !=(TextDataValidation left, TextDataValidation right) => !(left == right);

        /// <inheritdoc />
        public bool Equals(TextDataValidation other)
        {
            if (ReferenceEquals(this, other))
            {
                return true;
            }

            if (ReferenceEquals(other, null))
            {
                return false;
            }

            var result = this.Kind.IsEqualTo(other.Kind)
                      && this.Operator.IsEqualTo(other.Operator)
                      && this.Operand1Formula.IsEqualTo(other.Operand1Formula, StringComparer.Ordinal)
                      && this.Operand2Formula.IsEqualTo(other.Operand2Formula, StringComparer.Ordinal)
                      && this.IgnoreBlank.IsEqualTo(other.IgnoreBlank)
                      && this.ShowInputMessage.IsEqualTo(other.ShowInputMessage)
                      && this.InputMessageTitle.IsEqualTo(other.InputMessageTitle, StringComparer.Ordinal)
                      && this.InputMessageBody.IsEqualTo(other.InputMessageBody, StringComparer.Ordinal)
                      && this.ShowErrorAlertAfterInvalidDataIsEntered.IsEqualTo(other.ShowErrorAlertAfterInvalidDataIsEntered)
                      && this.ErrorAlertStyle.IsEqualTo(other.ErrorAlertStyle)
                      && this.ErrorAlertTitle.IsEqualTo(other.ErrorAlertTitle, StringComparer.Ordinal)
                      && this.ErrorAlertBody.IsEqualTo(other.ErrorAlertBody, StringComparer.Ordinal)
                      && this.ShowListDropdown.IsEqualTo(other.ShowListDropdown)
                      && this.Operand1TextValue.IsEqualTo(other.Operand1TextValue, StringComparer.Ordinal)
                      && this.Operand2TextValue.IsEqualTo(other.Operand2TextValue, StringComparer.Ordinal);

            return result;
        }

        /// <inheritdoc />
        public override bool Equals(object obj) => this == (obj as TextDataValidation);

        /// <inheritdoc />
        public override int GetHashCode() => HashCodeHelper.Initialize()
            .Hash(this.Kind)
            .Hash(this.Operator)
            .Hash(this.Operand1Formula)
            .Hash(this.Operand2Formula)
            .Hash(this.IgnoreBlank)
            .Hash(this.ShowInputMessage)
            .Hash(this.InputMessageTitle)
            .Hash(this.InputMessageBody)
            .Hash(this.ShowErrorAlertAfterInvalidDataIsEntered)
            .Hash(this.ErrorAlertStyle)
            .Hash(this.ErrorAlertTitle)
            .Hash(this.ErrorAlertBody)
            .Hash(this.ShowListDropdown)
            .Hash(this.Operand1TextValue)
            .Hash(this.Operand2TextValue)
            .Value;

        /// <inheritdoc />
        public new TextDataValidation DeepClone() => (TextDataValidation)this.DeepCloneInternal();

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithKind(DataValidationKind kind)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = kind,
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithOperator(DataValidationOperator @operator)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = @operator,
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithOperand1Formula(string operand1Formula)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = operand1Formula,
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithOperand2Formula(string operand2Formula)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = operand2Formula,
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithIgnoreBlank(bool ignoreBlank)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = ignoreBlank,
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithShowInputMessage(bool showInputMessage)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = showInputMessage,
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithInputMessageTitle(string inputMessageTitle)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = inputMessageTitle,
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithInputMessageBody(string inputMessageBody)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = inputMessageBody,
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithShowErrorAlertAfterInvalidDataIsEntered(bool showErrorAlertAfterInvalidDataIsEntered)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = showErrorAlertAfterInvalidDataIsEntered,
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithErrorAlertStyle(DataValidationErrorAlertStyle errorAlertStyle)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = errorAlertStyle,
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithErrorAlertTitle(string errorAlertTitle)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = errorAlertTitle,
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithErrorAlertBody(string errorAlertBody)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = errorAlertBody,
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public override DataValidation DeepCloneWithShowListDropdown(bool showListDropdown)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = showListDropdown,
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Operand1TextValue" />.
        /// </summary>
        /// <param name="operand1TextValue">The new <see cref="Operand1TextValue" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="TextDataValidation" /> using the specified <paramref name="operand1TextValue" /> for <see cref="Operand1TextValue" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public TextDataValidation DeepCloneWithOperand1TextValue(string operand1TextValue)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = operand1TextValue,
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <summary>
        /// Deep clones this object with a new <see cref="Operand2TextValue" />.
        /// </summary>
        /// <param name="operand2TextValue">The new <see cref="Operand2TextValue" />.  This object will NOT be deep cloned; it is used as-is.</param>
        /// <returns>New <see cref="TextDataValidation" /> using the specified <paramref name="operand2TextValue" /> for <see cref="Operand2TextValue" /> and a deep clone of every other property.</returns>
        [SuppressMessage("Microsoft.Design", "CA1002:DoNotExposeGenericLists")]
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [SuppressMessage("Microsoft.Design", "CA1054:UriParametersShouldNotBeStrings")]
        [SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly")]
        [SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix")]
        [SuppressMessage("Microsoft.Naming", "CA1715:IdentifiersShouldHaveCorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords")]
        [SuppressMessage("Microsoft.Naming", "CA1719:ParameterNamesShouldNotMatchMemberNames")]
        [SuppressMessage("Microsoft.Naming", "CA1720:IdentifiersShouldNotContainTypeNames")]
        [SuppressMessage("Microsoft.Naming", "CA1722:IdentifiersShouldNotHaveIncorrectPrefix")]
        [SuppressMessage("Microsoft.Naming", "CA1725:ParameterNamesShouldMatchBaseDeclaration")]
        [SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms")]
        [SuppressMessage("Microsoft.Naming", "CA2204:Literals should be spelled correctly")]
        [SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic")]
        public TextDataValidation DeepCloneWithOperand2TextValue(string operand2TextValue)
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = operand2TextValue,
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        protected override DataValidation DeepCloneInternal()
        {
            var result = new TextDataValidation
                             {
                                 Kind                                    = this.Kind.DeepClone(),
                                 Operator                                = this.Operator.DeepClone(),
                                 Operand1Formula                         = this.Operand1Formula?.DeepClone(),
                                 Operand2Formula                         = this.Operand2Formula?.DeepClone(),
                                 IgnoreBlank                             = this.IgnoreBlank.DeepClone(),
                                 ShowInputMessage                        = this.ShowInputMessage.DeepClone(),
                                 InputMessageTitle                       = this.InputMessageTitle?.DeepClone(),
                                 InputMessageBody                        = this.InputMessageBody?.DeepClone(),
                                 ShowErrorAlertAfterInvalidDataIsEntered = this.ShowErrorAlertAfterInvalidDataIsEntered.DeepClone(),
                                 ErrorAlertStyle                         = this.ErrorAlertStyle.DeepClone(),
                                 ErrorAlertTitle                         = this.ErrorAlertTitle?.DeepClone(),
                                 ErrorAlertBody                          = this.ErrorAlertBody?.DeepClone(),
                                 ShowListDropdown                        = this.ShowListDropdown.DeepClone(),
                                 Operand1TextValue                       = this.Operand1TextValue?.DeepClone(),
                                 Operand2TextValue                       = this.Operand2TextValue?.DeepClone(),
                             };

            return result;
        }

        /// <inheritdoc />
        [SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        public override string ToString()
        {
            var result = Invariant($"OBeautifulCode.Excel.TextDataValidation: Kind = {this.Kind.ToString() ?? "<null>"}, Operator = {this.Operator.ToString() ?? "<null>"}, Operand1Formula = {this.Operand1Formula?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Operand2Formula = {this.Operand2Formula?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, IgnoreBlank = {this.IgnoreBlank.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ShowInputMessage = {this.ShowInputMessage.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, InputMessageTitle = {this.InputMessageTitle?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, InputMessageBody = {this.InputMessageBody?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ShowErrorAlertAfterInvalidDataIsEntered = {this.ShowErrorAlertAfterInvalidDataIsEntered.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ErrorAlertStyle = {this.ErrorAlertStyle.ToString() ?? "<null>"}, ErrorAlertTitle = {this.ErrorAlertTitle?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ErrorAlertBody = {this.ErrorAlertBody?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, ShowListDropdown = {this.ShowListDropdown.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Operand1TextValue = {this.Operand1TextValue?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}, Operand2TextValue = {this.Operand2TextValue?.ToString(CultureInfo.InvariantCulture) ?? "<null>"}.");

            return result;
        }
    }
}